--liquibase formatted sql

--changeset a.khaustov:1
create table asset_contract
(
    id       bigint primary key generated by default as identity,
    exchange_id bigint not null,
    constraint fk_exchange_info_exchange_id
        foreign key (exchange_id)
            references exchange(id),
    symbol varchar(255),
    currency varchar(255),
    asset varchar(255),
    quantity_precision double precision,
    price_precision double precision,
    fee_rate double precision,
    maker_fee_rate double precision,
    taker_fee_rate double precision,
    trade_min_limit double precision,
    trade_min_quantity double precision,
    trade_min_usdt double precision,
    max_long_leverage bigint,
    max_short_leverage bigint
);


