--liquibase formatted sql

--changeset a.khaustov:1
create table user_symbol_leverage
(
    id       bigint primary key generated by default as identity,
    exchange_id bigint not null,
    constraint fk_user_symbol_leverage_exchange_id
        foreign key (exchange_id)
            references exchange(id),
    user_info_id bigint not null,
    constraint fk_user_symbol_leverage_user_info_id
        foreign key (user_info_id)
            references user_info(id),
    symbol varchar(255),
    long_leverage bigint,
    short_leverage bigint
);


