--liquibase formatted sql

--changeset a.khaustov:1
create table user_info
(
    id         bigint primary key generated by default as identity,
    api_key    varchar(255),
    secret_key varchar(255),
    exchange_name varchar(255),
    username varchar(255) not null unique
);




